name: Github Repo Widgets
author: re5et
category: Widgets
tags: [github, hovercards]
docs: http://github.com/re5et/github-repo-widgets
demo: http://re5et.github.com/projects/github-repo-widgets/demo/
current: 0.1.5